# Generated by Django 5.2 on 2025-05-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contrasenia',
            field=models.CharField(default=5, max_length=20),
            preserve_default=False,
        ),
    ]
