# Generated by Django 5.2 on 2025-05-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClases', '0002_estudiante_contrasenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='dni',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='username',
            field=models.CharField(default=5, max_length=40),
            preserve_default=False,
        ),
    ]
